name: Readme Workflow

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Waka Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False
          SHOW_PROJECTS: True
          SHOW_SHORT_INFO: False
          SHOW_TIMEZONE: False
          SHOW_OS: True
          SHOW_EDITORS : False
          SHOW_LANGUAGE : False
