name: Readme Workflow

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Waka Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False
          SHOW_PROJECTS: True
          SHOW_SHORT_INFO: False
          SHOW_TIMEZONE: False
          SHOW_OS: False
          SHOW_EDITORS : True
          SHOW_LANGUAGE : False
          SHOW_PROFILE_VIEWS: False
          SHOW_COMMIT: True
          SHOW_LINES_OF_CODE: False
          SHOW_DAYS_OF_WEEK: True
          SHOW_LANGUAGE_PER_REPO: False
